name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    label: 'Feature 🎁'
  - title: '💣 Breaking Change'
    label: 'Breaking Change 💣'
  - title: '🐛 Bug Fixes'
    label: 'Bug 🐛'
  - title: '📝 Documentation'
    label: 'Documentation 📝'
  - title: '🔨 Maintenance'
    label: 'Maintenance 🔨'
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## Getting Vanilla Framework

  Install with NPM: https://www.npmjs.com/package/vanilla-framework
  Visit the documentation at https://docs.vanillaframework.io

  ## New in Vanilla v$RESOLVED_VERSION

  $CHANGES
