name: Publish Vanilla release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - uses: actions/upload-artifact@v1
        with:
          name: vanilla.css
          path: build/css/build.css
      - name: Read Vanilla version from package.json
        run: node -p "require('./package.json').version" > VANILLA_VERSION
      - uses: actions/upload-artifact@v1
        with:
          name: VANILLA_VERSION
          path: VANILLA_VERSION

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-assets:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install upload-assets snap
        run: sudo snap install upload-assets
      - name: Read Vanilla version from package.json
        run: node -p "require('./package.json').version" > VANILLA_VERSION
      - name: Upload
        run: upload-assets --url-path vanilla-framework-version-$(cat VANILLA_VERSION).min.css build/css/build.css
        env:
          UPLOAD_ASSETS_API_TOKEN: ${{secrets.UPLOAD_ASSETS_API_TOKEN}}
